In [29]:
import pandas as pd

## Hyperparameter Tuning on Look-back Horizon n

            The folowing parameters are fixed:
            hr = 'KF'
            constant = True
            metric = 'sharpe_ratio'
            signal, entry, exit = 'ecdf', 0.05, 0.5
            window = 30
            select best 10 stocks.
            The following params are tuned:
            n: look back years
            n_largest: n largest stocks in sharpe ratio to select
            n_sample" number of stocks
            unique_tickers: require unique stocks acrossing multple pairs or not

In [6]:
res1 =pd.read_pickle('res1.pkl')
res1[['n', 'n_sample', 'rand_state', 'unique_tickers']] = pd.DataFrame(res1['params'].tolist())
res1 = res1.drop('params', axis = 1)
res1.head()

,n_largest,sr,cumr,pairs,n,n_sample,rand_state,unique_tickers
0,10,3.043589,1.487361,"[(NTRS, CMCSA), (NSC, TER), (CVX, CCL), (TGP, ...",0.5,100,0,True
1,5,2.984221,1.766853,"[(VLO, EFX), (VICR, FIBK), (AEIS, PG), (HIW, M...",0.5,100,0,True
2,10,1.985974,1.519057,"[(CVX, CAJ), (SSNC, GTE), (SSNC, SCL), (WD, UC...",0.5,100,0,False
3,5,1.666228,1.687396,"[(GSK, SCL), (TDS, CDNS), (SCL, AIV), (AXP, UC...",0.5,100,0,False
4,10,0.491010,1.067485,"[(DEO, EPR), (BXP, NNI), (IDXX, DEI), (BOH, SB...",0.5,100,1,True

In [38]:
# get 1.
res1.groupby(['n_sample', 'n', 'unique_tickers', 'n_largest']).mean().reset_index().drop('rand_state', axis = 1)
# get 2.
res1.groupby(['n_sample', 'n', 'n_largest', 'unique_tickers', ]).mean().reset_index().drop('rand_state', axis = 1)
# get 3
res1.loc[res1['unique_tickers'] == True].groupby(['n_sample', 'n', 'n_largest']).mean()\
.reset_index().drop(['rand_state', 'unique_tickers'], axis = 1)
# get 4
res1.loc[res1['unique_tickers'] == True].groupby(['n_sample', 'n', 'n_largest']).min()\
.reset_index().drop(['rand_state', 'unique_tickers', 'pairs'], axis = 1)
res1.loc[res1['unique_tickers'] == True].groupby(['n_sample', 'n', 'n_largest']).max()\
.reset_index().drop(['rand_state', 'unique_tickers', 'pairs'], axis = 1)

                              sr      cumr  rand_state  unique_tickers
n_sample n   n_largest
100      0.5 5          0.445259  1.089795           0            True
             10         0.491010  1.067485           0            True
         3.0 5          0.210979  1.021780           0            True
             10         0.731187  1.102446           0            True
         6.0 5         -0.019272  0.980636           0            True
             10         0.669445  1.083869           0            True
500      0.5 25         0.431710  1.086652           0            True
             50         0.431710  1.086652           0            True
         3.0 25         0.624007  1.176602           0            True
             50         1.094930  1.199715           0            True
         6.0 25         1.292294  1.087709           0            True
             50         1.351974  1.103580           0            True
900      0.5 45         0.586700  1.163407           0            True
             90         0.586700  1.163407           0            True
         3.0 45         0.791622  1.173549           0            True
             90         0.938202  1.164828           0            True
         6.0 45         1.153397  1.100911           0            True
             90         1.153397  1.100911           0            True

1. largest n_largest always increases performance. Thus, I might need to further increase n_largest to get better perfermance.
2. unique_tickers=false can generate large negative cumulative returns. The reseason is, with unique_tickers=false, one stock can be selected across multipple pairs, and then one wrong bet can wipe out portfolio. In a word, poor diversification with unique_tickers=Flase. Thus, the recommendation is to use unique_tickers = True always.
3. a. When performance is measured by sharpe ratio, there is a matching principle: small(large) n_sample matches with small(large) look-balck period generate better result. This might be because of overfitting when n_sample and look-back period are mismatched.
3. b. When performance is measured by cumulative return, small n_sample and small n have higher cum_r.
4. small-small have higher max_cumr depending on sample, yet min_cum_r is roughly the same as large-large.

It  seems that small look-back period with large cap is the way to go.

# Will Selecting More Pairs Have Better Performance

In [41]:
pd.read_pickle('res2.pkl')

      n  dateset  n_largest        sr      cumr  n_actual_pairs
0   0.5   152122          2  1.324212  1.233941               2
1   0.5   152122          5  1.109194  1.128043               5
2   0.5   152122         10  1.468544  1.162690              10
3   0.5   152122         16  1.013601  1.094568              16
4   0.5  2461363         40  2.397441  1.275053              40
5   0.5  2461363         80  2.463696  1.261204              80
6   0.5  2461363        161  3.455632  1.297095             161
7   0.5  2461363        241  2.986113  1.297386             241
8   0.5  5232160         78  3.618338  1.634744              78
9   0.5  5232160        157  3.858444  1.519834             157
10  0.5  5232160        315  4.077208  1.478675             315
11  0.5  5232160        472  4.112903  1.434135             472

In [42]:
pd.read_pickle('res3.pkl')

      n  dateset  n_largest        sr      cumr  n_actual_pairs
0   0.5   152122         10  1.468544  1.162690              10
1   0.5   152122         20  1.116853  1.099247              20
2   0.5   152122         30  1.150954  1.094034              27
3   0.5   152122         40  1.150954  1.094034              27
4   0.5   152122         50  1.150954  1.094034              27
5   0.5   152122         60  1.150954  1.094034              27
6   0.5  2461363         10  1.966622  1.359322              10
7   0.5  2461363         20  2.194484  1.286268              20
8   0.5  2461363         30  2.347179  1.307267              30
9   0.5  2461363         40  2.397441  1.275053              40
10  0.5  2461363         50  2.222525  1.239202              50
11  0.5  2461363         60  2.022884  1.226079              60
12  0.5  5232160         10  1.834066  1.629099              10
13  0.5  5232160         20  1.750014  1.763320              20
14  0.5  5232160         30  2.256155  1.697325              30
15  0.5  5232160         40  2.504969  1.641230              40
16  0.5  5232160         50  2.870303  1.603341              50
17  0.5  5232160         60  3.489818  1.649082              60

More pairs generate higher sharpe ratio, but not cum_r roughtly the same. This implies that it might work with smaller pairs when performance is measured by cum_r

In [44]:
pd.read_pickle('res4.pkl').sort_values('sr')

,n,dateset,n_largest,look_ahead,hr,OLS_window,constant,sr,cumr,n_actual_pairs
19,1.0,152122,20,0.5,OLS,40,True,-2.851274,0.378691,20
18,1.0,152122,10,0.5,OLS,40,True,-2.819170,0.201117,10
34,1.0,152122,10,0.5,OLS,60,True,-2.789798,0.491530,10
35,1.0,152122,20,0.5,OLS,60,True,-2.785386,0.713162,20
17,0.5,152122,20,0.5,OLS,40,True,-2.641043,0.408872,20
23,1.0,152122,20,1.0,OLS,40,True,-2.425889,0.004313,20
38,1.0,152122,10,1.0,OLS,60,True,-2.333005,-0.019705,10
16,0.5,152122,10,0.5,OLS,40,True,-2.236862,0.436518,10
2,1.0,152122,10,0.5,OLS,20,True,-2.218497,0.344588,10
39,1.0,152122,20,1.0,OLS,60,True,-2.202517,0.031875,20
22,1.0,152122,10,1.0,OLS,40,True,-1.950700,0.053909,10
33,0.5,152122,20,0.5,OLS,60,True,-1.940227,0.815532,20
36,0.5,152122,10,1.0,OLS,60,True,-1.695312,0.008995,10
6,1.0,152122,10,1.0,OLS,20,True,-1.099224,0.624520,10
37,0.5,152122,20,1.0,OLS,60,True,-0.967735,-2132.903372,20
41,0.5,152122,20,0.5,OLS,60,False,-0.965840,0.944921,20
40,0.5,152122,10,0.5,OLS,60,False,-0.816921,0.932557,10
45,0.5,152122,20,1.0,OLS,60,False,-0.700889,0.917077,20
32,0.5,152122,10,0.5,OLS,60,True,-0.652259,0.911078,10
43,1.0,152122,20,0.5,OLS,60,False,-0.528058,0.970023,20
47,1.0,152122,20,1.0,OLS,60,False,-0.517385,0.935913,20
44,0.5,152122,10,1.0,OLS,60,False,-0.128850,0.966812,10
42,1.0,152122,10,0.5,OLS,60,False,-0.059300,0.997685,10
27,1.0,152122,20,0.5,OLS,40,False,-0.023895,0.997567,20
46,1.0,152122,10,1.0,OLS,60,False,0.108163,1.005822,10
21,0.5,152122,20,1.0,OLS,40,True,0.398574,0.000931,20
31,1.0,152122,20,1.0,OLS,40,False,0.415260,1.036135,20
25,0.5,152122,20,0.5,OLS,40,False,0.428207,1.017312,20
20,0.5,152122,10,1.0,OLS,40,True,0.651081,-0.010728,10
26,1.0,152122,10,0.5,OLS,40,False,0.690856,1.029852,10
5,0.5,152122,20,1.0,OLS,20,True,0.786972,0.247816,20
7,1.0,152122,20,1.0,OLS,20,True,0.795747,-0.004686,20
28,0.5,152122,10,1.0,OLS,40,False,0.799205,1.094582,10
4,0.5,152122,10,1.0,OLS,20,True,0.868347,0.112425,10
29,0.5,152122,20,1.0,OLS,40,False,0.909404,1.087773,20
24,0.5,152122,10,0.5,OLS,40,False,1.057060,1.043526,10
30,1.0,152122,10,1.0,OLS,40,False,1.090593,1.129459,10
3,1.0,152122,20,0.5,OLS,20,True,1.266178,0.646752,20
1,0.5,152122,20,0.5,OLS,20,True,1.691056,3.995938,20
0,0.5,152122,10,0.5,OLS,20,True,1.908579,10.300543,10
15,1.0,152122,20,1.0,OLS,20,False,2.336785,1.233958,20
14,1.0,152122,10,1.0,OLS,20,False,2.450394,1.292999,10
13,0.5,152122,20,1.0,OLS,20,False,2.581385,1.381629,20
10,1.0,152122,10,0.5,OLS,20,False,2.647429,1.149110,10
12,0.5,152122,10,1.0,OLS,20,False,2.799908,1.424051,10
11,1.0,152122,20,0.5,OLS,20,False,2.901507,1.160591,20
9,0.5,152122,20,0.5,OLS,20,False,3.092121,1.241643,20
8,0.5,152122,10,0.5,OLS,20,False,3.238318,1.243541,10

1. always set constant = False, that is, for OLS, no constant needed.
2. smaller OLS look-back window generates better result.

In [45]:
pd.read_pickle('res5.pkl').sort_values('sr')

,n,dateset,n_largest,look_ahead,hr,OLS_window,constant,sr,cumr,n_actual_pairs
2,1.0,152122,10,0.5,KF,20,True,0.607888,1.030202,10
10,1.0,152122,10,0.5,KF,20,False,0.616457,1.038057,10
14,1.0,152122,10,1.0,KF,20,False,1.200726,1.130997,10
0,0.5,152122,10,0.5,KF,20,True,1.208049,1.069808,10
6,1.0,152122,10,1.0,KF,20,True,1.252592,1.116924,10
1,0.5,152122,20,0.5,KF,20,True,1.305994,1.059192,20
9,0.5,152122,20,0.5,KF,20,False,1.382331,1.066468,20
4,0.5,152122,10,1.0,KF,20,True,1.509991,1.158716,10
13,0.5,152122,20,1.0,KF,20,False,1.738833,1.145844,20
11,1.0,152122,20,0.5,KF,20,False,1.761030,1.111141,20
8,0.5,152122,10,0.5,KF,20,False,1.769256,1.093082,10
3,1.0,152122,20,0.5,KF,20,True,1.797825,1.062986,20
5,0.5,152122,20,1.0,KF,20,True,1.869120,1.149412,20
12,0.5,152122,10,1.0,KF,20,False,2.032759,1.197259,10
15,1.0,152122,20,1.0,KF,20,False,2.372578,1.254306,20
7,1.0,152122,20,1.0,KF,20,True,2.450005,1.167741,20

1. No obvious difference in sharpe ratio between constant = True and constant = False.
2. However, comparing KF and OLS, the lowest sr for KF is higher compared with the lowest sr for OLS.

In [46]:
pd.read_pickle('res6.pkl').sort_values('sr')

,n,dateset,n_largest,look_ahead,hr,OLS_window,constant,sr,cumr,n_actual_pairs
2,0.5,152122,30,0.5,KF,20,False,0.594813,1.032178,27
3,0.5,152122,40,0.5,KF,20,False,0.594813,1.032178,27
4,1.0,152122,10,0.5,KF,20,False,0.616457,1.038057,10
15,0.5,152122,40,1.0,KF,20,False,1.178730,1.109517,27
14,0.5,152122,30,1.0,KF,20,False,1.178730,1.109517,27
16,1.0,152122,10,1.0,KF,20,False,1.200726,1.130997,10
11,1.5,152122,40,0.5,KF,20,False,1.291621,1.053457,27
10,1.5,152122,30,0.5,KF,20,False,1.291621,1.053457,27
28,1.0,152122,10,1.5,KF,20,False,1.307116,1.190791,10
1,0.5,152122,20,0.5,KF,20,False,1.382331,1.066468,20
27,0.5,152122,40,1.5,KF,20,False,1.478275,1.184046,27
26,0.5,152122,30,1.5,KF,20,False,1.478275,1.184046,27
13,0.5,152122,20,1.0,KF,20,False,1.738833,1.145844,20
5,1.0,152122,20,0.5,KF,20,False,1.761030,1.111141,20
0,0.5,152122,10,0.5,KF,20,False,1.769256,1.093082,10
9,1.5,152122,20,0.5,KF,20,False,1.769263,1.068164,20
23,1.5,152122,40,1.0,KF,20,False,1.867302,1.145339,27
22,1.5,152122,30,1.0,KF,20,False,1.867302,1.145339,27
25,0.5,152122,20,1.5,KF,20,False,1.953108,1.224647,20
12,0.5,152122,10,1.0,KF,20,False,2.032759,1.197259,10
8,1.5,152122,10,0.5,KF,20,False,2.049980,1.093713,10
7,1.0,152122,40,0.5,KF,20,False,2.100962,1.121059,27
6,1.0,152122,30,0.5,KF,20,False,2.100962,1.121059,27
32,1.5,152122,10,1.5,KF,20,False,2.197114,1.303502,10
20,1.5,152122,10,1.0,KF,20,False,2.204936,1.210996,10
35,1.5,152122,40,1.5,KF,20,False,2.220084,1.238997,27
34,1.5,152122,30,1.5,KF,20,False,2.220084,1.238997,27
29,1.0,152122,20,1.5,KF,20,False,2.261823,1.324393,20
24,0.5,152122,10,1.5,KF,20,False,2.303174,1.316701,10
17,1.0,152122,20,1.0,KF,20,False,2.372578,1.254306,20
21,1.5,152122,20,1.0,KF,20,False,2.397700,1.192386,20
33,1.5,152122,20,1.5,KF,20,False,2.472225,1.281121,20
30,1.0,152122,30,1.5,KF,20,False,2.507925,1.320562,27
31,1.0,152122,40,1.5,KF,20,False,2.507925,1.320562,27
19,1.0,152122,40,1.0,KF,20,False,2.618580,1.250057,27
18,1.0,152122,30,1.0,KF,20,False,2.618580,1.250057,27

n =1 and lookahead =1, pairs = 30 as optimal value.

In [48]:
pd.read_pickle('res7.pkl').sort_values('sr', ascending = False)

,n,dateset,n_largest,look_ahead,hr,OLS_window,constant,state_mean,state_cov,trans_var,observ_var,sr,cumr,n_actual_pairs
193,1,152122,20,1,KF,20,False,0.00,0.000,0.001,2,3.091030,1.274360,20
197,1,152122,20,1,KF,20,False,0.05,0.000,0.001,2,3.091030,1.274360,20
201,1,152122,20,1,KF,20,False,0.10,0.000,0.001,2,3.091030,1.274360,20
205,1,152122,20,1,KF,20,False,0.00,0.001,0.001,2,3.091030,1.274360,20
298,1,152122,20,1,KF,20,False,0.10,0.000,0.005,4,2.671317,1.212864,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,1,152122,10,1,KF,20,False,0.05,0.001,0.000,5,-0.304667,0.950995,10
104,1,152122,10,1,KF,20,False,0.10,0.000,0.000,4,-0.404626,0.959593,10
8,1,152122,10,1,KF,20,False,0.10,0.000,0.000,2,-0.404626,0.959593,10
56,1,152122,10,1,KF,20,False,0.10,0.000,0.000,3,-0.404626,0.959593,10
152,1,152122,10,1,KF,20,False,0.10,0.000,0.000,5,-0.404626,0.959593,10

Optimal paramter will be mean = 0, var1 =0.001, and var2 = 0.001 and var3 = 2